server:
  port: 22334

spring:
  application:
    name: operation
  profiles:
    active: dev
    include: default-${spring.profiles.active}

tenant:
  exclusionTable:
    - t_goods
    - t_goods_sku
